add_newline = false
format = "$hostname$directory$git_branch$git_state$git_status$git_metrics$line_break$character"

[character]
error_symbol = "[➜](bold red)"
success_symbol = "[➜](bold green)"
vicmd_symbol = "[<](bold green)"

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "cyan"
renamed = ""
deleted = ""
stashed = "≡"

[git_metrics]
format = "([+$added]($added_style)/[-$deleted]($deleted_style))"
added_style = "bold green"
deleted_style = "bold red"

