display-name = "Damian Myrda"
downloads-dir = "~/Downloads"

[gmail]
default = true
email = "monkey.damianek@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "monkey.damianek@gmail.com"
imap-passwd-cmd = "pass show gmail"
imap-notify-query = "not seen"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "monkey.damianek@gmail.com"
smtp-passwd-cmd = "pass show gmail"

[gmail.folder-aliases]
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"
